// <auto-generated />
using System;
using BuddyCloudCoreApi21.DAL.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuddyCloudCoreApi21.DAL.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20180621202826_RecreateDb")]
    partial class RecreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BuddyCloudCoreApi21.Core.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Password");

                    b.Property<string>("Salt");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("BuddyCloudCoreApi21.Core.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ItemName");

                    b.Property<int>("Qty");

                    b.Property<Guid>("StockId");

                    b.Property<int>("Total");

                    b.Property<int>("TransactionId");

                    b.HasKey("Id");

                    b.HasIndex("TransactionId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("BuddyCloudCoreApi21.Core.Models.Stock", b =>
                {
                    b.Property<Guid>("StockId")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("DateAdded");

                    b.Property<string>("Description");

                    b.Property<decimal>("MarkupPrice");

                    b.Property<int>("Qty");

                    b.Property<Guid>("SKU");

                    b.Property<decimal>("SalePrice");

                    b.Property<decimal>("SellingPrice");

                    b.Property<string>("StockName");

                    b.Property<decimal>("UnitPrice");

                    b.Property<Guid>("UserId");

                    b.HasKey("StockId");

                    b.HasIndex("UserId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("BuddyCloudCoreApi21.Core.Models.Transactions", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BankName");

                    b.Property<string>("CustomerName");

                    b.Property<string>("PaymentType");

                    b.Property<bool>("Status");

                    b.Property<decimal>("Subtotal");

                    b.Property<DateTime>("TransactionDate");

                    b.Property<Guid>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("BuddyCloudCoreApi21.Core.Models.Order", b =>
                {
                    b.HasOne("BuddyCloudCoreApi21.Core.Models.Transactions", "Transaction")
                        .WithMany("Orders")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuddyCloudCoreApi21.Core.Models.Stock", b =>
                {
                    b.HasOne("BuddyCloudCoreApi21.Core.Identity.ApplicationUser", "User")
                        .WithMany("Stocks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuddyCloudCoreApi21.Core.Models.Transactions", b =>
                {
                    b.HasOne("BuddyCloudCoreApi21.Core.Identity.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
